### ISSUE TITLE
Error running patcher

### ISSUE THREAD

**Issue by arshesney** [Piranha91/Under-There-#2]
I'm getting an exception when building the patch with Synthesis:
[log-20210213.txt](https://github.com/Piranha91/Under-There-/files/5975543/log-20210213.txt)

810 NPCs were assigned to the Default group because their definitions could not be matched to any custom groups.
1136 classifiers could not be matched to any group definitions defined in the settings file.
See the log for details: T:\mods\SSE\Synthesis\Data\Under-There-\failedAssignmentLog.txt
[failedAssignmentLog.txt](https://github.com/Piranha91/Under-There-/files/5975510/failedAssignmentLog.txt)

System.ArgumentException: BODT type not expected on versions >= 44
   at Mutagen.Bethesda.Skyrim.Internals.BodyTemplateBinaryOverlay.CustomFactory(OverlayStream stream, BinaryOverlayFactoryPackage package)
   at Mutagen.Bethesda.Skyrim.Internals.ArmorAddonBinaryOverlay.GetBodyTemplateCustom()
   at Mutagen.Bethesda.Skyrim.Internals.ArmorAddonBinaryOverlay.get_BodyTemplate()
   at UnderThere.Program.patchBodyARMAslots(List`1 usedSlots, List`1 patchableRaces, IPatcherState`2 state) in C:\Users\user\AppData\Local\Temp\Synthesis\be662628-d842-4b1c-9aaf-37f102fdc8b2\Git\932ebeaa-e5fa-49ae-86f9-7d2338be5e30\Runner\UnderThere\Program.cs:line 622
   at UnderThere.Program.RunPatch(IPatcherState`2 state) in C:\Users\user\AppData\Local\Temp\Synthesis\be662628-d842-4b1c-9aaf-37f102fdc8b2\Git\932ebeaa-e5fa-49ae-86f9-7d2338be5e30\Runner\UnderThere\Program.cs:line 59
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.<>c__DisplayClass11_0`2.<<AddPatch>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.Run(RunSynthesisMutagenPatcher args, ModKey exportKey, RunPreferences preferences)
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.<>c__DisplayClass15_0.<<Run>b__1>d.MoveNext()
Synthesis.Bethesda.Execution.CliUnsuccessfulRunException: Error running solution patcher

**Comment by Piranha91** [comment]
Interesting, I've never seen this error before. Could you please tell me

a) if the error still occurs for you on a blank MO2 profile (assuming you're using MO2)
b) what your load order is?

**Comment by arshesney** [comment]
Load order: https://modwat.ch/u/arshesney1/plugins
I changed underwear mod for the time being, "Underwear from NPCs" wasn't installed and there was "Equipable Underwear for Everyone".
On a cleasnish (just USSEP, SkyUI, BodySlide CBBE and Live Another Life) profile there is no error. It has to be a plugin, if there's a way to output the offending one (or the FromID at least) it would be great.

**Comment by Piranha91** [comment]
I just pushed a new version that tells you the FormID that it's trying to patch - please try it and let me know where it gets stuck. It's in the Dev branch of the git repository; please configure the patcher versioning as shown here: https://imgur.com/awCZS6p

**Comment by arshesney** [comment]
[failedAssignmentLog.txt](https://github.com/Piranha91/Under-There-/files/6009743/failedAssignmentLog.txt)
Hopefully I ran it correctly: Synthesis keeps resetting to main when I start it and changing the branch seems to lose MO2 VFS hook

**Comment by Piranha91** [comment]
Sorry, the failed assignment log doesn't tell me why it's crashing - it just tells me which factions aren't defined in the settings file (these NPCs just get default underwear instead of randomized). To see what's crashing I would have to see the most recent file in your Synthesis\logs folder.

**Comment by arshesney** [comment]
[log-20210219.txt](https://github.com/Piranha91/Under-There-/files/6012569/log-20210219.txt)
Here, kinda a mess,because I ran it a few times

**Comment by Piranha91** [comment]
Hmm, very strange - it didn't execute the controlled fail but still crashed. Ok, let's try this. I just pushed a new version to github that lists FormID-by-FormID what it's patching. Before runnning the patcher again, edit the UnderThereConfig.json file as shown here so that it has "bVerboseMode: true" at the end: https://imgur.com/kNaAifd

It should list everything that it's patching as shown in the screenshot, the last thing that it lists is what should be causing the crash.

Warning: there's a bug in the current version of Synthesis (14.1) that causes it to wipe the settings file before running - Noggog is working on a fix. In the meantime, you may need to use a previous version of Synthesis (13.2 I know works fine). It's not the Synthesis version that the patcher is "set to use", but the version of the actual synthesis.exe. If your UnderThereConfig.json file suddenly changes from ~18kb to 6kb or 1 kb and the patcher errors out due to a json error, that's what's causing it and it will hopefully be resolved today or tomorrow.

**Comment by arshesney** [comment]
Ok, synthesis is 0.13.2, config json is 18kb after adding verbose
[log-20210219.txt](https://github.com/Piranha91/Under-There-/files/6013334/log-20210219.txt)
I've run a few tests, in my main setup it stops after theDBinitaites.esp, after that there are archery gameplay overhaul, animated armoury and bikini armors, but they seem fine by themselves

**Comment by Piranha91** [comment]
Hmm, can you clarify where your theDBinitiates.esp is from? I downloaded it from the nexus (https://www.nexusmods.com/skyrimspecialedition/mods/9508) and there are no armor addons, and record xx004F33 doesn't exist. Are you using a special version of that esp?

**Comment by arshesney** [comment]
Ah, sorry, I'm also using Pandorable's initiates, which replaces the esp

**Comment by Piranha91** [comment]
I'm sorry, I just tested all 3 versions of Pandorable's Initiates and the patcher ran fine through all three of them. Does it consistently crash on that esp for you?

**Comment by arshesney** [comment]
Sorry, didin't have much time for testing.
I've changed my load order a bit, the patcher now stops after a different mod [Caesia](https://www.nexusmods.com/skyrimspecialedition/mods/13389), a follower mod. Which is not the problematic one, because by itself it is fine, and the next one it amazing world of bikini armors remastered, which I can see it processed before Caesia in the log file.

[Uploading log-20210301.txt…]()

**Comment by stephen-dahl** [comment]
I am getting the same error but only if I have my Mator Smash patch in
